theme: jekyll-theme-minimal
lang: es-UY
title: Brisa.uy
description: Aventuras del velero Brisa navegando rumbo a Uruguay
author: Douglas Lovell
logo: assets/images/brisa_logo_600.png
license: <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Licencia Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a>Esta obra está bajo una <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Licencia Creative Commons Atribución-NoComercial-CompartirIgual 4.0 Internacional</a>.

plugins:
 - jekyll-feed
 - jekyll-seo-tag

header_pages:
 - artículos.md
 - sobre.md
 - index.md
